# SPDX-FileCopyrightText: 2026 Dominik Wombacher <dominik@wombacher.cc>
#
# SPDX-License-Identifier: CC0-1.0

version: "2"

linters:
  default: standard
  enable:
    - gosec

formatters:
  enable:
    - gofmt
